### ISSUE TITLE
MonicasFlagToC: Flags are shown as 'resolved' in Safari

### ISSUE THREAD

**Issue by Undo1** [Shog9/flagfilter#4]
The script installed in Chrome shows the expected result for an NAA flag, while Safari shows only "1 resolved flags" (although the flags are not resolved). This is shown in the Safari (but not Chrome) console:

`RangeError: Invalid Date`:

![screen shot 2018-01-27 at 9 52 33 pm](https://user-images.githubusercontent.com/5162342/35479127-69487cba-03ac-11e8-9899-d8ef56399d68.png)

**Comment by Shog9** [comment]
I have no access to Safari; run these in a console & let me know the results, please:

    (new Date()).toISOString();

    (new Date(new Date()).toISOString();

    (new Date("2018-01-27 01:15:04Z")).toISOString();

**Comment by Undo1** [comment]
Note that I corrected the second one with a closing paren in the middle:

```
> (new Date()).toISOString();
< "2018-01-28T20:38:21.535Z"

> (new Date(new Date())).toISOString();
< "2018-01-28T20:39:07.232Z"

> (new Date("2018-01-27 01:15:04Z")).toISOString();
< RangeError: Invalid Date
```

**Comment by Undo1** [comment]
This is slightly ugly, but appears to work in Safari and Chrome:

```
> (new Date("2018-01-27 01:15:04Z".replace(" ", "T"))).toISOString();
< "2018-01-27T01:15:04.000Z"
```
